### ISSUE TITLE
HTML File Name

### ISSUE THREAD

**Issue by philsinatra** [jel99/idm231#1]
You'll want to rename your primary HTML file `pokemonzodiac.html` ➡️ `index.html`.

**Comment by kryptodrex** [comment]
For this, I didn't name it index.html because it's going to sit as a separate page on my portfolio site which I already have the domain for. So it'll be lunine.net/pokemonzodiac.html

**Comment by philsinatra** [comment]
If that's the case, you will create a new folder called `pokemonzodiac`. Within that folder, which is a totally new project, you can use `index.html` for your main HTML page, and your stylesheets can be more conventional names like `screen.css` etc. (if desired).

The idea will be to have this project and all of it's assets in a unique folder so that you can move/host the zodiac wherever you want, and not worry about duplicate or conflicting file names.

**Comment by kryptodrex** [comment]
Ahhh ok. That makes sense. I'll do that.
